### PR TITLE
x509: add ExtensionsMap to Certificate.

### PR DESCRIPTION
**Pull request by cpu**
A new `ExtensionsMap` field is added on the `x509.Certificate` object. This field maps from the string form of a `pkix.Extension.Id` OID (e.g. "1.3.6.1.5.5.7.1.1") to a raw `pkix.Extension` value. This lets relying code check if a certificate has a given extension by OID in O(1) time.

To accomplish this the `parseCertificate` function is updated to populate this map at the same time as parsing the existing `x509.Certificate.Extensions` field. The `x509.JSONCertificate` type and `x509.Certificate.MarshalJSON` function are **not** updated to avoid duplicate and unnecessary extension output in JSON.

Resolves https://github.com/zmap/zcrypto/issues/198

### CODE REVIEW

**Comment by cpu** [comment]
I'll start on the `zlint` update PR once this is all merged up and I can bump the `go.mod` ref.

**Comment by zakird** [comment]
Hrm, actually, I think we probably don't want to output these in the JSON. That would lead to every extension showing up twice in the output.

**Comment by cpu** [comment]
@zakird :+1: I'll back out the JSON updates and fix the PR description.

**Comment by cpu** [comment]
>  I think we probably don't want to output these in the JSON.

Fixed in 9e2dce4

**Comment by zakird** [comment]
🙌

**Comment by zakird** [comment]
Is there the potential to have certificates that have multiple extensions with the same OID? How do we want to handle? It seems like this might be a construction issue and the type of thing we'd want to handle in ZLint.

**Comment by cpu** [comment]
> How do we want to handle? It seems like this might be a construction issue and the type of thing we'd want to handle in ZLint.

I think ignoring the possibility for the purpose of the `x509.Certificate.ExtensionsMap` and then adding a lint on the `Zlint` side that iterates `x509.Certificate.Extensions` and checks for duplicates would be my preference. I can't think of any adverse side effects from this approach but I'm open to input if I missed something. Any duplicate OIDs squashed to one entry in the `x509.Certificate.ExtensionsMap` would be present in duplicate in the original `x509.Certificate.Extensions` slice.

**Comment by zakird** [comment]
That's fine with me. The alternative would be to map str -> []ext but if that's _never_ the expected behavior, then that seems burdensome to API users. I'll merge this and we can handle that in ZLint if that sounds good.

**Comment by cpu** [comment]
I added a small clarification note to the `ExtensionMap` Godoc comment since I think its worth capturing this accepted limitation in the doc string: 105ca31

**Comment by cpu** [comment]
>  The alternative would be to map str -> []ext but if that's never the expected behavior, then that seems burdensome to API users.

To close the loop here [RFC 5280 Sec 4.2](https://tools.ietf.org/html/rfc5280#section-4.2) confirms this expectation is reasonable and something we can lint for in `zlint` at the error level:

>  A certificate MUST NOT include more than one instance of a particular extension.

**Comment by cpu** [comment]
> I think ignoring the possibility for the purpose of the x509.Certificate.ExtensionsMap and then adding a lint on the Zlint side that iterates x509.Certificate.Extensions and checks for duplicates would be my preference.

@zakird Turns out there is already a lint for this :tada:: https://github.com/zmap/zlint/blob/master/lints/lint_ext_duplicate_extension.go It's O(n^2) but I think that's OK for this one lint.

**Pull request merged**
