### PR TITLE
Update ChromeCiphers []uint16

### PR DESCRIPTION
**Pull request by ealashwali**
The current Chrome (and possibly others) ciphersuites list is outdated. For example, it contains Rc4 ciphers, missing SHA384 ciphers, etc. 
The new edits make the list is compatible with Chrome Version 67.0.3396.99. 
Namely, update ciphers are the following 16 ciphers (NOTE:  Chrome Version 67.0.3396.99 contains a cipher named "GREASE" (0xcaca) which I ignored):
(0x13,0x01),(0x13,0x02),(0x13,0x03),(0xc0,0x2b),(0xc0,0x2f),(0xc0,0x2c),(0xc0,0x30),(0xcc,0xa9),(0xcc,0xa8),(0xc0,0x13),(0xc0,0x14),(0x00,0x9c),(0x00,0x9d),(0x00,0x2f),(0x00,0x35),(0x00,0x0a)

The ciphers hex. codes and cipher names, are obtained from: https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml

### CODE REVIEW

**Comment by zakird** [comment]
These are going to need to be implemented and supported with the framework before they can be listed here. Which of these are currently supported with the backend crypto code?

**Comment by ealashwali** [comment]
These are currently supported:
```
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
TLS_RSA_WITH_AES_128_GCM_SHA256
TLS_RSA_WITH_AES_128_CBC_SHA
TLS_RSA_WITH_AES_256_CBC_SHA
TLS_RSA_WITH_3DES_EDE_CBC_SHA
```
These are newly added:
```
TLS_AES_128_GCM_SHA256
TLS_AES_256_GCM_SHA384
TLS_CHACHA20_POLY1305_SHA256
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_RSA_WITH_AES_256_GCM_SHA384
```

**Comment by ealashwali** [comment]
Thanks for your reply. If there is an estimate for the time this takes, I will appreciate let me know. I am sorry for this but nor sure if I should wait. If it takes long time it is better know this.

**Comment by zakird** [comment]
As noted in the other issue, we don't have an immediate timeline for adding new chrome ciphers.

**Comment by ealashwali** [comment]
The continuous-integration test says there is missing comma (I just found out there should be comma after the last ciphersuite in the list). Shall I make a new pull request? will this make any difference? thanks.

**Comment by zakird** [comment]
I'm closing this since it cannot be merged without a significant backend implementation of these ciphers.

**Pull request closed without merging**
