### PR TITLE
Added "Adobe Authentic Document Trust" EKU

### PR DESCRIPTION
**Pull request by chrisbn**
As mentioned in #324 , this adds support for the Adobe EKU.

### CODE REVIEW

**Comment by christopher-henderson** [comment]
Thank you @chrisbn!

So this is apparently a machine generated file (see [x509/extended_key_usage_gen.go](https://github.com/zmap/zcrypto/blob/599ec18ecbac3129a5ed383d15188060229b500d/x509/extended_key_usage_gen.go#L297)), which itself gets its input from a CSV in [zmap/constants](https://raw.githubusercontent.com/zmap/constants/master/x509/extended_key_usage.csv).

From what I can tell, you have successfully replicated what that code-gen script would have generated anyways (expect for some details like exact ordering), however I think it would be wise to simply update that CSV with the following contents...

```csv
...
...
1.2.840.113583.1.1.5,Adobe,adobe-authentic-document-trust,
...
...
```

...and then use the code-gen script to update this PR (this code generation scheme predates my contributions to ZMap, so I'm unsure if manually updating this file without updating the `constants` repository would cause a misalignment/breakage somewhere).

Unfortunately, I am not a contributor on the `zmap/constants` repo and can't help push that through. @zakird could I get added so that I can help see Christophe to completion on this?

**Comment by christopher-henderson** [comment]
@zakird could you review my request to become a contributor to [zmap/constants](https://github.com/zmap/constants) so that I can get Chrisophe unblocked on this change?

**Comment by zakird** [comment]
I've added flint-maintainers as repository maintainers for zmap/constants, so you should be good.

**Review by christopher-henderson — APPROVED** [review]
Thank you for the patience @chrisbn! We got the changes to the upstream `zmap/constants` repository merged and re-ran the OID generation script. The only differences I can see are some ordering the definitions, however in the interest of getting this over the line that is perfectly fine for now.

**Pull request merged**
