### PR TITLE
Update x509 to latest 1.9, keeping modifications and simplify ct

### PR DESCRIPTION
**Pull request by tadukurow**
This is a large PR that aims to separate some of the stdlib imported code from the modifications made by zcrypto. Introducing this separation should make it easier to track upstream and in many cases simplify some code, as the stdlib asn1 and x509 libraries have evolved quite a bit. 
It solves or facilitates https://github.com/zmap/zcrypto/issues/1, https://github.com/zmap/zcrypto/issues/9, https://github.com/zmap/zcrypto/issues/106

It also breaks the dependency of the x509 and tls package on the ct package. The reasoning is that the ct package contains it's own x509 and is difficult to extract and upgrade. So the code necessary to define and Deserialize SCTs has been moved to x509/ct.
This does mean upstream packages would need to update their import paths. 
Personally I think the ct package should not be part of the zcrypto repo as it introduces a lot of problems when trying to track upstream for asn1 and x509. if ct was removed as hinted in https://github.com/zmap/zcrypto/issues/9, the ct deserialization code used in tls and x509 code go back to the normal import path and updates would be needed. But I don't know enough about the usage patterns of CT within zmap.

First I determined that the original x509 port seems to be from around 2015, not sure what incremental updates were done. Unfortunately no changelog with revisions was documented. 
Then I updated it to latest 1.9 release (documented in README.md), preserving all modifications in files called $name_modified.go.
Test files weren't updated or modified and are passing. 
I left some notes where it seems zcrypto could align with the stdlib with some updates. 

This work should also allow for an easy upgrade path to 1.10 and newer versions.

### CODE REVIEW

**Comment by justinbastress** [comment]
@tadukurow we are still looking into the best way to move forward here with regard to upstream golang crypto changes.

**Comment by tadukurow** [comment]
@justinbastress thanks for the update. 

I'm happy to change anything on the PR if necessary. 

Also would you be able to share anything on the direction you're debating/planning to take?

**Comment by tadukurow** [comment]
Hi is there any update on this? 

We're looking to move to 1.10 as it has some features we need. 
Would a PR that simply makes the build pass on 1.10 and 1.9 as suggested on #109, be considered at this point? 
https://github.com/google/certificate-transparency-go/commit/391726f8973ddb3521ab1a462bd55a35c6f67f0b

**Comment by justinbastress** [comment]
@tadukurow this should go in as soon as I find the right way to pin other apps (e.g. zgrab) to the existing version.

In the meantime -- would you be able to share the context in which you are using zcrypto? e.g. just as a dependency for zlint, or something more involved?

**Comment by tadukurow** [comment]
@justinbastress that's good news. 

we use zcrypto strictly as a dependency for zlint, but would like to keep contributing to zlint like the previous work by @szank.

**Pull request merged**
