### PR TITLE
Fix external ClientHello import

### PR DESCRIPTION
**Pull request by mtury**
Hi,
This is a fix for https://github.com/zmap/zgrab/pull/223
The connection config needs to be updated after a raw ClientHello import, as when using a ClientHello fingerprint. Unless we do that, there is a high chance of discrepancies between the ServerHello received (based on the ClientHello we sent) and whatever zgrab is ready to negotiate (based on the config)!
The patch seems pretty straightforward but I haven't checked every field with the right test connections yet. At least I could see it worked as expected when providing cipher suites different from the defaultConfig ones. ;)

### CODE REVIEW

**Comment by dadrian** [comment]
Offhand the patch seems fine. @bvandersloot, can you review since you wrote the original `ClientFingerprintConfiguration` code?

@mtury it looks like this caused a test to fail, I'm not sure why. Can you investigate?

**Comment by bvandersloot** [comment]
I don't believe this touches any of my codepaths or fails my tests. It just looks related to `ClientFingerprintConfiguration` because of where the first function was inserted and how GitHub rendered this.

**Comment by mtury** [comment]
As @bvandersloot says, the patch sits next to the fingerprint code (and it looks similar), but actually their execution is mutually exclusive.

There is no failing test when I run it on my side, and one of the fails here seems to be related to a time sensitive TCP connection. Could you restart the build maybe?

**Comment by dadrian** [comment]
Thanks!

**Comment by mtury** [comment]
Well thank you for your work here. :)

**Pull request merged**
