### PR TITLE
Fix CHACHA20_POLY1305 Ciphers

### PR DESCRIPTION
**Pull request by MercysJest**
This PR attempts to fix an issue with the implemented `CHACHA20_POLY1305` ciphers.

When attempting TLS handshakes using the `zgrab2 tls` module with these ciphers:

```
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256
```
Servers will return the `bad_record_mac` alert.

### CODE REVIEW

**Comment by zakird** [comment]
What's the best way to test this?

**Comment by MercysJest** [comment]
> What's the best way to test this?

Testing against the top ~3K hosts from Alexa, I have not seen a successful handshake with these ciphers. 

`printf "google.com\ncloudflare.com" | ./zgrab2 tls --cipher-suite="0xcca8, 0xcca9, 0xccaa" | jq . -M | grep '"error":'`

It appears that the build check fails above. I am using the package `http://golang.org/x/crypto/chacha20poly1305` and my `go version go1.12.6 linux/amd64`.

**Comment by cpu** [comment]
> It appears that the continuous integration build check fails.

:wave: @MercysJest 

Yup, the root cause in this case is from a missing vendored dep:
```
$ go install -mod=vendor -v ./...
tls/cipher_suites.go:21:2: cannot find package "." in:
	/home/travis/gopath/src/github.com/zmap/zcrypto/vendor/golang.org/x/crypto/chacha20poly1305
```

CI builds using vendored dependencies (`-mod=vendor`). With Go 1.12.x you'll need to run `GO111MODULE=on go get golang.org/x/crypto/chacha20poly1305` in the root of the zcrypto project in your Gopath to add the dependency to the [go.mod](https://github.com/zmap/zcrypto/blob/master/go.mod) manifest. Afterwards run `GO111MODULE=on go mod vendor` and add the vendored library and the updated `go.mod`/`go.sum` to this branch. That should fix the CI failure above.

**Comment by zakird** [comment]
Thanks all. @MercysJest can you run `go fmt` as Cody mentioned, then we can go ahead and merge. Easy enough that I figure we might as well just take care of now.

**Comment by MercysJest** [comment]
I ran `go fmt` and it appears to have altered

```
conn.go
tls_handshake.go
tls_names.go
```
Is this still desired?

**Comment by codyprime** [comment]
> I ran `go fmt` and it appears to have altered
> 
> ```
> conn.go
> tls_handshake.go
> tls_names.go
> ```
> 
> Is this still desired?

I just ran `gofmt -w` against the 4 files you touched, and cipher_suites.go was the only one that show differences.  In my opinion, I wouldn't feel compelled add additional files to the PR that you didn't touch originally.

**Comment by cpu** [comment]
> In my opinion, I wouldn't feel compelled to add additional files to the PR that you didn't touch originally.

Agreed. Here's a separate PR that cleans up the existing files with `gofmt -s` and starts enforcing it in CI: https://github.com/zmap/zcrypto/pull/194

**Comment by MercysJest** [comment]
@codyprime I am not seeing a change on my side?
```
λ go fmt cipher_suites.go 
λ gofmt -w -s cipher_suites.go 
λ git diff
λ
```

**Comment by zakird** [comment]
@cpu +1 for adding to zlint

**Comment by MercysJest** [comment]
@codyprime I ran the `go fmt` and pushed the changes.

**Comment by zakird** [comment]
@MercysJest I wanted to note that I'm super impressed that you got to the bottom of this and had a PR merged without any requested changes less than 24 hours from when we identified the problem around CHACHA ciphers. Really nice job. 🙌

**Pull request merged**
